version: '3'
services:
  app:
    image: palomarosa/projeto-docker-linx:v0
    ports:
     - "8080:8080"
    volumes:
      - .:/usr/share/nginx/html  # Mapeia o diretório local ./html para o diretório no container, assim não precisa derrubar o container para refletir as alterações
      # - ./pages/register.html:/usr/share/nginx/html/register.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mapeia a configuração do nginx localmente 